### ISSUE TITLE
acpartner v3 error - model not specified

### ISSUE THREAD

**Issue by mouth4war** [syssi/xiaomiplug#13]
If model is specified or not in config, this error shows after initializing message.

```
 [homeassistant.components.switch] Error while setting up platform xiaomi_miio
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/switch/xiaomi_miio.py", line 160, in async_setup_platform
    plug = AirConditioningCompanionV3(host, token, model=model)
TypeError: __init__() got an unexpected keyword argument 'model'
```

**Comment by syssi** [comment]
Next try. :-)
