### ISSUE TITLE
acpartner v3 error invalid literal

### ISSUE THREAD

**Issue by mouth4war** [syssi/xiaomiplug#14]
Now getting this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "/srv/homeassistant/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 259, in __repr__
    self.air_condition_remote,
  File "/srv/homeassistant/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 164, in air_condition_remote
    return int(self.air_condition_model[4:8].hex())
ValueError: invalid literal for int() with base 10: 'ffffffff'
Call stack:
  File "/srv/homeassistant/bin/hass", line 11, in <module>
    sys.exit(main())
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/__main__.py", line 389, in main
    exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/async_.py", line 29, in asyncio_run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
    handle._run()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/switch/xiaomi_miio.py", line 541, in async_update
    _LOGGER.debug("Got new state: %s", state)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
```

**Comment by syssi** [comment]
This needs to be fixed at python-miio: https://github.com/rytilahti/python-miio/pull/446

**Comment by mouth4war** [comment]
I implemented locally and it fixed the issue!

**Comment by vcheng99** [comment]
thanks for the work, that's what I wanted.

but I got this error:
 Configuration invalid
 Check config
 Invalid config for [switch.xiaomi_miio]: value is not allowed for dictionary value @ data['model']. Got 'lumi.acpartner.v3'. (See ?, line ?). Please check the docs at https://home-assistant.io/components/switch.xiaomi_miio/

I am using HA 0.88.2
 put switch.py under config\custom_components\xiaomi_miio

my configuration.yaml:
 switch:
•platform: xiaomi_miio
 name: AC Partner V3 Socket Living Room
 host: 192.168.30.94
 token: e6485a97d3fcbc123508db716708fae8
 model: lumi.acpartner.v3

** strange that if I put other values as model, it will not show error

please help

**Comment by syssi** [comment]
Do you use the custom component? The official HA component isn't updated right now.

**Comment by vcheng99** [comment]
Yes, 

 

I am using HA 0.88.2

put switch.py under config\custom_components\xiaomi_miio

 

my configuration.yaml:

switch:

•platform: xiaomi_miio

name: AC Partner V3 Socket Living Room

host: 192.168.30.94

token: e6485a97d3fcbc123508db716708fae8

model: lumi.acpartner.v3

 

** strange that if I put other models as model, it will not show error

 

please help

 

Victor Cheng 

vDesk Ltd.

Mobile: 91013221

Email: victor@vdesk.com.hk

**Comment by vcheng99** [comment]
Finally got it to work, just some typo mistake , thanks very much for your module

Victor Cheng
vDesk Ltd.

Sebastian Muszynski <notifications@github.com> 於 2019年3月4日 上午2:04 寫道：

Do you use the custom component? The official HA component isn't updated right now.

**Comment by vcheng99** [comment]
Do you have any support on using the limo.acoartner.v3 as gateway?

Since I cannot get they key for this device, only token

Victor Cheng
vDesk Ltd.

Sebastian Muszynski <notifications@github.com> 於 2019年3月4日 上午2:04 寫道：

Do you use the custom component? The official HA component isn't updated right now.

**Comment by syssi** [comment]
No. `xiaomi_aqara` is the way to go.

**Comment by vcheng99** [comment]
lumi.acpartner.v3 worked before with custom_components\xiaomi_miio\switch.py
however since upgrade to 0.90.2, failed to work with configuration check error
