### ISSUE TITLE
Plugin not working with HomeAssistant 2023.2 (Python 3.12) No module named 'imp'

### ISSUE THREAD

**Issue by nealeydee** [syssi/xiaomiplug#27]
SInce the release of HomeAssistant 2024.2, unable to connect to my Xiaomi Power Strip.
This seems to be caused by the Python version upgrade in HA (3.12) which no longer supports the imp module.

Hers is an extract of the HomeAssistant Logs

2024-02-10 17:21:14.305 ERROR (MainThread) [homeassistant.config] Platform error: switch - No module named 'imp'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config.py", line 1518, in async_process_component_config
platform = p_integration.get_platform(domain)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 994, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/xiaomi_miio_plug/switch.py", line 17, in <module>
from miio import (
File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
from miio.device import Device, DeviceStatus # isort: skip
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
from .miioprotocol import MiIOProtocol
File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
import construct
File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
from construct.core import *
File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

**Comment by syssi** [comment]
I've prepared a new release. Please give it a try: https://github.com/syssi/xiaomiplug/releases/tag/2024.2.0.0

**Comment by nealeydee** [comment]
Wow! That was fast. and it works. Thank you.
